import type { Dish } from "./types";

// Canonical dishes. This file is the reason the app can answer "1 kadhai paneer
// and 3 tandoori roti — who sells that combination cheapest near me?"
//
// A meta-aggregator's genuinely hard problem is not the fee arithmetic, it is
// deciding that "Kadai Paneer", "Kadhai Paneer" and "Karahi Paneer" are one
// orderable thing while "Paneer Butter Masala" is a different one. `aliases`
// carries that, and every kitchen in restaurants.ts references a dish by id
// rather than restating a name — so a spelling never fragments a comparison.
//
// `counterPrice` is the anchor, not a price anyone pays: it is what a mid-tier
// kitchen charges at its own counter. Each restaurant scales it by its
// `priceTier` and may override it outright. Every channel price in the app is
// derived from that, so a change here moves all four columns coherently.

export const DISHES: Dish[] = [
  {
    id: "kadhai-paneer",
    name: "Kadhai Paneer",
    aliases: ["kadai paneer", "karahi paneer", "kadhai panner", "paneer kadai"],
    description: "Paneer with capsicum and onion in a coarse-ground kadhai masala",
    category: "North Indian mains",
    veg: true,
    vegan: false,
    counterPrice: 220,
    packagingCost: 15,
    popular: true,
  },
  {
    id: "paneer-butter-masala",
    name: "Paneer Butter Masala",
    aliases: ["pbm", "paneer makhani", "butter paneer", "paneer makhanwala"],
    description: "Cottage cheese in a slow-cooked tomato, butter and cashew gravy",
    category: "North Indian mains",
    veg: true,
    vegan: false,
    counterPrice: 230,
    packagingCost: 15,
    popular: true,
  },
  {
    id: "dal-makhani",
    name: "Dal Makhani",
    aliases: ["kaali dal", "black dal", "maa ki dal"],
    description: "Black lentils simmered overnight, finished with cream",
    category: "North Indian mains",
    veg: true,
    vegan: false,
    counterPrice: 190,
    packagingCost: 15,
  },
  {
    id: "dal-tadka",
    name: "Dal Tadka",
    aliases: ["yellow dal", "dal fry", "tadka dal"],
    description: "Yellow lentils with a cumin and dry-chilli tempering",
    category: "North Indian mains",
    veg: true,
    vegan: false,
    counterPrice: 150,
    packagingCost: 15,
  },
  {
    id: "chole",
    name: "Chole",
    aliases: ["chana masala", "chholey", "pindi chole", "chickpea curry"],
    description: "Chickpeas in an onion-tomato masala, cooked in oil",
    category: "North Indian mains",
    veg: true,
    vegan: true,
    counterPrice: 160,
    packagingCost: 15,
  },
  {
    id: "shahi-paneer",
    name: "Shahi Paneer",
    aliases: ["shahee paneer", "paneer shahi"],
    description: "Paneer in a mild cashew-and-cream gravy",
    category: "North Indian mains",
    veg: true,
    vegan: false,
    counterPrice: 240,
    packagingCost: 15,
  },
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    aliases: ["murgh makhani", "chicken makhani"],
    description: "Tandoori chicken in a tomato-butter gravy",
    category: "North Indian mains",
    veg: false,
    vegan: false,
    counterPrice: 330,
    packagingCost: 20,
    popular: true,
  },
  {
    id: "tandoori-roti",
    name: "Tandoori Roti",
    aliases: ["roti", "tandoori rooti", "plain roti"],
    description: "Whole-wheat, clay oven, no butter",
    category: "Breads",
    veg: true,
    vegan: true,
    counterPrice: 15,
    packagingCost: 3,
    popular: true,
  },
  {
    id: "butter-naan",
    name: "Butter Naan",
    aliases: ["naan", "makhani naan"],
    description: "Leavened white flour bread, brushed with butter",
    category: "Breads",
    veg: true,
    vegan: false,
    counterPrice: 45,
    packagingCost: 4,
  },
  {
    id: "laccha-paratha",
    name: "Laccha Paratha",
    aliases: ["lachha paratha", "layered paratha"],
    description: "Multi-layered flaky wheat paratha",
    category: "Breads",
    veg: true,
    vegan: false,
    counterPrice: 55,
    packagingCost: 4,
  },
  {
    id: "jeera-rice",
    name: "Jeera Rice",
    aliases: ["cumin rice", "zeera rice"],
    description: "Basmati tossed with cumin",
    category: "Rice",
    veg: true,
    vegan: true,
    counterPrice: 120,
    packagingCost: 12,
  },
  {
    id: "veg-biryani",
    name: "Veg Biryani",
    aliases: ["vegetable biryani", "veg dum biryani"],
    description: "Dum-cooked rice with seasonal vegetables and fried onion",
    category: "Rice",
    veg: true,
    vegan: false,
    counterPrice: 210,
    packagingCost: 20,
  },
  {
    id: "chicken-biryani",
    name: "Chicken Biryani",
    aliases: ["chicken dum biryani", "murgh biryani", "hyderabadi biryani"],
    description: "Long-grain rice and bone-in chicken, sealed and dum-cooked",
    category: "Rice",
    veg: false,
    vegan: false,
    counterPrice: 280,
    packagingCost: 25,
    popular: true,
  },
  {
    id: "paneer-tikka",
    name: "Paneer Tikka",
    aliases: ["tandoori paneer", "paneer tikka dry"],
    description: "Marinated paneer, capsicum and onion off the skewer",
    category: "Starters",
    veg: true,
    vegan: false,
    counterPrice: 260,
    packagingCost: 18,
  },
  {
    id: "veg-thali",
    name: "Veg Thali",
    aliases: ["thali", "vegetarian thali", "north indian thali"],
    description: "Two sabzi, dal, rice, four rotis, salad, sweet",
    category: "Thali",
    veg: true,
    vegan: false,
    counterPrice: 200,
    packagingCost: 25,
    popular: true,
  },
  {
    id: "chole-bhature",
    name: "Chole Bhature",
    aliases: ["chhole bhature", "bhature"],
    description: "Two fried bhature with chole and pickled onion",
    category: "Thali",
    veg: true,
    vegan: false,
    counterPrice: 140,
    packagingCost: 15,
  },
  {
    id: "masala-dosa",
    name: "Masala Dosa",
    aliases: ["dosa", "masaala dosa", "mysore masala dosa"],
    description: "Crisp crepe with potato masala, sambar and chutney",
    category: "South Indian",
    veg: true,
    vegan: false,
    counterPrice: 110,
    packagingCost: 15,
  },
  {
    id: "gulab-jamun",
    name: "Gulab Jamun (2 pcs)",
    aliases: ["gulab jaamun", "jamun"],
    description: "Khoya dumplings in cardamom syrup",
    category: "Dessert",
    veg: true,
    vegan: false,
    counterPrice: 70,
    packagingCost: 8,
  },
  {
    id: "sweet-lassi",
    name: "Sweet Lassi",
    aliases: ["lassi", "meethi lassi"],
    description: "Thick set curd blended with sugar, malai on top",
    category: "Beverages",
    veg: true,
    vegan: false,
    counterPrice: 80,
    packagingCost: 8,
  },
  {
    id: "masala-chai",
    name: "Masala Chai",
    aliases: ["chai", "tea", "cutting chai"],
    description: "Boiled tea with ginger and cardamom",
    category: "Beverages",
    veg: true,
    vegan: false,
    counterPrice: 30,
    packagingCost: 5,
  },
];

export const DISH_BY_ID = new Map(DISHES.map((dish) => [dish.id, dish]));

/** Free-text match over name, aliases and category — what the search box uses. */
export function matchDishes(query: string): Dish[] {
  const needle = query.trim().toLowerCase();
  if (!needle) return [];
  return DISHES.filter((dish) =>
    [dish.name, dish.category, ...dish.aliases].some((field) =>
      field.toLowerCase().includes(needle),
    ),
  );
}
