import type { Restaurant } from "./types";

// Six kitchens across four metros, chosen to cover the cases where the answer
// changes: a pure-veg thali house, a biryani specialist, a discount-heavy
// national burger chain, a premium cafe that is not on ONDC at all, a South
// Indian tiffin room with a very low average order value, and a highway-style
// dhaba that skipped Zomato.
//
// `basePrice` is what the kitchen itself charges. Every platform price in the
// UI is derived from it — see pricing.ts. `markupAdjustment` is the deviation
// from the platform's headline commission in absolute rate terms: a chain with
// negotiating power pays less than a single outlet, and both pay less on ONDC
// where the network fee is a few percent by design.

export const RESTAURANTS: Restaurant[] = [
  {
    id: "annapurna",
    name: "Annapurna Thali House",
    tagline: "Unlimited North Indian thalis since 1978",
    cuisines: ["North Indian", "Thali"],
    city: "Delhi",
    area: "Karol Bagh",
    pureVeg: true,
    rating: 4.4,
    prepMinutes: 22,
    listedOn: ["swiggy", "zomato", "ondc"],
    markupAdjustment: { swiggy: 0.01, zomato: 0, ondc: 0 },
    memberPartner: ["swiggy", "zomato"],
    offers: [
      { platform: "zomato", label: "40% off up to ₹80", percent: 40, cap: 80, minOrder: 199 },
      { platform: "swiggy", label: "30% off up to ₹75", percent: 30, cap: 75, minOrder: 199 },
    ],
    items: [
      {
        id: "annapurna-premium-thali",
        name: "Premium Rajasthani Thali",
        description: "Dal baati churma, gatte ki sabzi, two rotis, rice, salad, sweet",
        basePrice: 249,
        veg: true,
        vegan: false,
        category: "Thali",
        packagingCost: 25,
        popular: true,
      },
      {
        id: "annapurna-paneer-butter-masala",
        name: "Paneer Butter Masala",
        description: "Cottage cheese in a slow-cooked tomato and cashew gravy",
        basePrice: 210,
        veg: true,
        vegan: false,
        category: "Main course",
        packagingCost: 20,
        popular: true,
      },
      {
        id: "annapurna-dal-tadka",
        name: "Dal Tadka",
        description: "Yellow lentils tempered with ghee, cumin and dry chilli",
        basePrice: 145,
        veg: true,
        vegan: false,
        category: "Main course",
        packagingCost: 15,
      },
      {
        id: "annapurna-chana-masala",
        name: "Punjabi Chana Masala",
        description: "Chickpeas simmered in onion-tomato masala, cooked in oil",
        basePrice: 155,
        veg: true,
        vegan: true,
        category: "Main course",
        packagingCost: 15,
      },
      {
        id: "annapurna-jeera-rice",
        name: "Jeera Rice",
        description: "Basmati tossed with cumin",
        basePrice: 110,
        veg: true,
        vegan: true,
        category: "Rice & breads",
        packagingCost: 12,
      },
      {
        id: "annapurna-tandoori-roti",
        name: "Tandoori Roti (2 pcs)",
        description: "Whole wheat, clay oven, no butter",
        basePrice: 40,
        veg: true,
        vegan: true,
        category: "Rice & breads",
        packagingCost: 5,
      },
      {
        id: "annapurna-gulab-jamun",
        name: "Gulab Jamun (2 pcs)",
        description: "Khoya dumplings in cardamom syrup",
        basePrice: 70,
        veg: true,
        vegan: false,
        category: "Dessert",
        packagingCost: 10,
      },
    ],
  },
  {
    id: "biryani-junction",
    name: "Biryani Junction",
    tagline: "Dum-cooked Hyderabadi biryani, sealed pots only",
    cuisines: ["Hyderabadi", "Biryani", "Mughlai"],
    city: "Hyderabad",
    area: "Banjara Hills",
    pureVeg: false,
    rating: 4.3,
    prepMinutes: 30,
    listedOn: ["swiggy", "zomato", "ondc"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.01, ondc: 0.005 },
    memberPartner: ["swiggy"],
    offers: [
      { platform: "swiggy", label: "50% off up to ₹100", percent: 50, cap: 100, minOrder: 249 },
      { platform: "zomato", label: "50% off up to ₹90", percent: 50, cap: 90, minOrder: 249 },
    ],
    items: [
      {
        id: "biryani-chicken-dum",
        name: "Chicken Dum Biryani (Full)",
        description: "Long-grain rice, bone-in chicken, saffron, served with raita and mirchi ka salan",
        basePrice: 320,
        veg: false,
        vegan: false,
        category: "Biryani",
        packagingCost: 30,
        popular: true,
      },
      {
        id: "biryani-veg-dum",
        name: "Veg Dum Biryani (Full)",
        description: "Seasonal vegetables and paneer, dum-cooked with ghee and fried onion",
        basePrice: 260,
        veg: true,
        vegan: false,
        category: "Biryani",
        packagingCost: 30,
        popular: true,
      },
      {
        id: "biryani-mutton-dum",
        name: "Mutton Dum Biryani (Full)",
        description: "Slow-cooked goat shoulder, whole spices, sealed pot",
        basePrice: 420,
        veg: false,
        vegan: false,
        category: "Biryani",
        packagingCost: 30,
      },
      {
        id: "biryani-chicken-65",
        name: "Chicken 65",
        description: "Fried, curry-leaf tempered, boneless",
        basePrice: 240,
        veg: false,
        vegan: false,
        category: "Starters",
        packagingCost: 20,
      },
      {
        id: "biryani-mirchi-salan",
        name: "Mirchi Ka Salan (Extra)",
        description: "Peanut and sesame gravy with long green chillies",
        basePrice: 70,
        veg: true,
        vegan: true,
        category: "Sides",
        packagingCost: 10,
      },
      {
        id: "biryani-double-ka-meetha",
        name: "Double Ka Meetha",
        description: "Fried bread pudding in reduced milk",
        basePrice: 95,
        veg: true,
        vegan: false,
        category: "Dessert",
        packagingCost: 12,
      },
    ],
  },
  {
    id: "burger-bhai",
    name: "Burger Bhai",
    tagline: "Desi-spiced burgers, 140 outlets nationwide",
    cuisines: ["Burgers", "Fast food", "American"],
    city: "Bengaluru",
    area: "Indiranagar",
    pureVeg: false,
    rating: 4.1,
    prepMinutes: 14,
    listedOn: ["swiggy", "zomato", "ondc"],
    // A national chain negotiates commission down by several points on both
    // aggregators — which is exactly why chain food is the case where ONDC's
    // advantage is smallest.
    markupAdjustment: { swiggy: -0.05, zomato: -0.04, ondc: 0 },
    memberPartner: ["swiggy", "zomato"],
    offers: [
      { platform: "swiggy", label: "60% off up to ₹120", percent: 60, cap: 120, minOrder: 249 },
      { platform: "zomato", label: "60% off up to ₹120", percent: 60, cap: 120, minOrder: 249 },
      { platform: "ondc", label: "10% off up to ₹40", percent: 10, cap: 40, minOrder: 199 },
    ],
    items: [
      {
        id: "burger-masala-chicken",
        name: "Masala Chicken Burger",
        description: "Fried chicken thigh, tandoori mayo, pickled onion",
        basePrice: 189,
        veg: false,
        vegan: false,
        category: "Burgers",
        packagingCost: 12,
        popular: true,
      },
      {
        id: "burger-aloo-tikki",
        name: "Aloo Tikki Burger",
        description: "Spiced potato patty, mint chutney, shredded cabbage",
        basePrice: 99,
        veg: true,
        vegan: true,
        category: "Burgers",
        packagingCost: 10,
        popular: true,
      },
      {
        id: "burger-paneer-makhani",
        name: "Paneer Makhani Burger",
        description: "Grilled paneer slab, makhani sauce, cheese slice",
        basePrice: 169,
        veg: true,
        vegan: false,
        category: "Burgers",
        packagingCost: 12,
      },
      {
        id: "burger-peri-fries",
        name: "Peri Peri Fries (Large)",
        description: "Skin-on fries, peri peri dust",
        basePrice: 129,
        veg: true,
        vegan: true,
        category: "Sides",
        packagingCost: 10,
      },
      {
        id: "burger-cola",
        name: "Cola (500 ml)",
        description: "Chilled bottle",
        basePrice: 60,
        veg: true,
        vegan: true,
        category: "Beverages",
        packagingCost: 5,
      },
      {
        id: "burger-choco-shake",
        name: "Thick Chocolate Shake",
        description: "Dairy ice cream, cocoa, whipped top",
        basePrice: 149,
        veg: true,
        vegan: false,
        category: "Beverages",
        packagingCost: 12,
      },
    ],
  },
  {
    id: "roastery-cafe",
    name: "The Roastery Coffee House",
    tagline: "Single-origin espresso and all-day plates",
    cuisines: ["Cafe", "Continental", "Desserts"],
    city: "Mumbai",
    area: "Bandra West",
    pureVeg: false,
    rating: 4.6,
    prepMinutes: 26,
    // Premium independents are the most common ONDC gap: the network's
    // catalogue skews towards chains and value kitchens.
    listedOn: ["swiggy", "zomato"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.02 },
    memberPartner: ["zomato"],
    offers: [{ platform: "zomato", label: "20% off up to ₹100", percent: 20, cap: 100, minOrder: 399 }],
    items: [
      {
        id: "roastery-truffle-pasta",
        name: "Truffle Mushroom Pasta",
        description: "Fettuccine, cream, wild mushroom, truffle oil",
        basePrice: 480,
        veg: true,
        vegan: false,
        category: "Mains",
        packagingCost: 35,
        popular: true,
      },
      {
        id: "roastery-chicken-bowl",
        name: "Grilled Chicken Power Bowl",
        description: "Quinoa, chicken breast, avocado, tahini",
        basePrice: 520,
        veg: false,
        vegan: false,
        category: "Mains",
        packagingCost: 35,
      },
      {
        id: "roastery-vegan-buddha",
        name: "Vegan Buddha Bowl",
        description: "Millet, roast pumpkin, chickpea, lemon-tahini dressing",
        basePrice: 440,
        veg: true,
        vegan: true,
        category: "Mains",
        packagingCost: 35,
        popular: true,
      },
      {
        id: "roastery-cold-brew",
        name: "Cold Brew (250 ml)",
        description: "18-hour steep, single origin, served black",
        basePrice: 260,
        veg: true,
        vegan: true,
        category: "Coffee",
        packagingCost: 18,
      },
      {
        id: "roastery-cappuccino",
        name: "Cappuccino",
        description: "Double shot, whole milk",
        basePrice: 230,
        veg: true,
        vegan: false,
        category: "Coffee",
        packagingCost: 18,
      },
      {
        id: "roastery-basque",
        name: "Basque Burnt Cheesecake",
        description: "Slice, salted caramel drizzle",
        basePrice: 380,
        veg: true,
        vegan: false,
        category: "Desserts",
        packagingCost: 25,
      },
    ],
  },
  {
    id: "dosa-darbar",
    name: "Dosa Darbar",
    tagline: "Filter coffee and crisp dosas, 6am to 11pm",
    cuisines: ["South Indian", "Tiffin"],
    city: "Chennai",
    area: "T. Nagar",
    pureVeg: true,
    rating: 4.5,
    prepMinutes: 16,
    listedOn: ["swiggy", "zomato", "ondc"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.02, ondc: 0.01 },
    memberPartner: ["swiggy"],
    offers: [{ platform: "swiggy", label: "40% off up to ₹60", percent: 40, cap: 60, minOrder: 149 }],
    items: [
      {
        id: "dosa-masala",
        name: "Masala Dosa",
        description: "Crisp crepe, potato masala, sambar and two chutneys",
        basePrice: 110,
        veg: true,
        vegan: false,
        category: "Dosa",
        packagingCost: 15,
        popular: true,
      },
      {
        id: "dosa-plain",
        name: "Plain Dosa",
        description: "No ghee, served with sambar and chutney",
        basePrice: 80,
        veg: true,
        vegan: true,
        category: "Dosa",
        packagingCost: 12,
      },
      {
        id: "dosa-idli",
        name: "Idli (3 pcs)",
        description: "Steamed rice cakes, sambar, coconut chutney",
        basePrice: 70,
        veg: true,
        vegan: true,
        category: "Tiffin",
        packagingCost: 12,
        popular: true,
      },
      {
        id: "dosa-vada",
        name: "Medu Vada (2 pcs)",
        description: "Fried urad dal doughnuts",
        basePrice: 65,
        veg: true,
        vegan: true,
        category: "Tiffin",
        packagingCost: 10,
      },
      {
        id: "dosa-pongal",
        name: "Ven Pongal",
        description: "Rice and moong dal, black pepper, cashew, ghee",
        basePrice: 95,
        veg: true,
        vegan: false,
        category: "Tiffin",
        packagingCost: 12,
      },
      {
        id: "dosa-filter-coffee",
        name: "Filter Coffee",
        description: "Decoction and boiled milk, davara set",
        basePrice: 45,
        veg: true,
        vegan: false,
        category: "Beverages",
        packagingCost: 8,
      },
    ],
  },
  {
    id: "punjabi-tadka",
    name: "Punjabi Tadka Dhaba",
    tagline: "Highway dhaba portions, city address",
    cuisines: ["North Indian", "Punjabi"],
    city: "Pune",
    area: "Koregaon Park",
    pureVeg: false,
    rating: 4.2,
    prepMinutes: 28,
    // Delisted from Zomato over commission — a real and increasingly common
    // reason a restaurant appears on only two of the three columns.
    listedOn: ["swiggy", "ondc"],
    markupAdjustment: { swiggy: 0.01, ondc: 0 },
    memberPartner: [],
    offers: [{ platform: "ondc", label: "12% off up to ₹70", percent: 12, cap: 70, minOrder: 299 }],
    items: [
      {
        id: "tadka-butter-chicken",
        name: "Butter Chicken (Half)",
        description: "Tandoori chicken in tomato-butter gravy",
        basePrice: 340,
        veg: false,
        vegan: false,
        category: "Main course",
        packagingCost: 25,
        popular: true,
      },
      {
        id: "tadka-paneer-butter-masala",
        name: "Paneer Butter Masala",
        description: "Malai paneer, cashew-tomato gravy, kasuri methi",
        basePrice: 265,
        veg: true,
        vegan: false,
        category: "Main course",
        packagingCost: 22,
        popular: true,
      },
      {
        id: "tadka-dal-makhani",
        name: "Dal Makhani",
        description: "Black lentils, overnight simmer, cream finish",
        basePrice: 220,
        veg: true,
        vegan: false,
        category: "Main course",
        packagingCost: 20,
      },
      {
        id: "tadka-chole",
        name: "Amritsari Chole",
        description: "Chickpeas, anardana, cooked in oil",
        basePrice: 190,
        veg: true,
        vegan: true,
        category: "Main course",
        packagingCost: 18,
      },
      {
        id: "tadka-butter-naan",
        name: "Butter Naan (2 pcs)",
        description: "Leavened, brushed with butter",
        basePrice: 90,
        veg: true,
        vegan: false,
        category: "Rice & breads",
        packagingCost: 8,
      },
      {
        id: "tadka-tandoori-roti",
        name: "Tandoori Roti (2 pcs)",
        description: "Plain, no butter",
        basePrice: 50,
        veg: true,
        vegan: true,
        category: "Rice & breads",
        packagingCost: 6,
      },
      {
        id: "tadka-lassi",
        name: "Sweet Lassi (Glass)",
        description: "Thick set curd, sugar, malai top",
        basePrice: 110,
        veg: true,
        vegan: false,
        category: "Beverages",
        packagingCost: 10,
      },
    ],
  },
];

export const RESTAURANT_BY_ID = new Map(RESTAURANTS.map((r) => [r.id, r]));

export const ALL_ITEMS = RESTAURANTS.flatMap((restaurant) =>
  restaurant.items.map((item) => ({ item, restaurant })),
);
