import type { MenuEntry, Restaurant } from "./types";

// Twenty-five kitchens across five localities, five per locality — so a search
// in any one of them returns a real comparison rather than a shortlist of one.
//
// NAMES ARE INVENTED. They are deliberately generic-sounding local names and
// not national chains, because every price in this repo is modelled rather than
// observed: attaching made-up prices to a recognisable brand would read as a
// factual claim about that business. The archetypes are real (a value
// bhojnalaya, a sweets-and-thali house, a highway-style dhaba, a hotel
// restaurant, a modern cafe) and that is what drives the pricing spread.
//
// `priceTier` multiplies each dish's canonical counter price from dishes.ts.
// That is what makes the same kadhai paneer ₹175 at a bhojnalaya and ₹320 at a
// hotel restaurant without restating 250 prices by hand — and a `priceOverride`
// is used only where a kitchen genuinely departs from its own tier, which is
// the interesting case rather than the common one.

/** Compact menu-entry helper — this file would be unreadable without it. */
const m = (dishId: string, priceOverride?: number, packagingOverride?: number): MenuEntry => ({
  dishId,
  priceOverride,
  packagingOverride,
});

// The North Indian core almost every kitchen here carries. Sharing it is what
// guarantees a five-way comparison for a typical "paneer + roti" search; a
// dataset where each kitchen sold something different would look richer and
// answer nothing.
const NORTH_CORE = [
  m("kadhai-paneer"),
  m("paneer-butter-masala"),
  m("dal-makhani"),
  m("dal-tadka"),
  m("chole"),
  m("tandoori-roti"),
  m("butter-naan"),
  m("jeera-rice"),
  m("gulab-jamun"),
  m("sweet-lassi"),
];

export const RESTAURANTS: Restaurant[] = [
  // ---------------------------------------------------------------- Dwarka --
  {
    id: "annapurna-bhojnalaya",
    name: "Annapurna Bhojnalaya",
    localityId: "dwarka",
    tagline: "Steel plates, ceiling fans, unchanged since 1991",
    cuisines: ["North Indian", "Thali"],
    pureVeg: true,
    rating: 4.0,
    prepMinutes: 18,
    distanceKm: 0.5,
    priceTier: 0.8,
    // Delisted from Zomato over commission — increasingly common at this tier,
    // and the reason the pickup column matters most for value kitchens.
    listedOn: ["swiggy", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.01 },
    memberPartner: [],
    offers: [{ channel: "ondc", label: "10% off up to ₹50", percent: 10, cap: 50, minOrder: 199 }],
    menu: [...NORTH_CORE, m("veg-thali", 150), m("chole-bhature"), m("laccha-paratha"), m("masala-chai")],
  },
  {
    id: "punjabi-rasoi",
    name: "Punjabi Rasoi",
    localityId: "dwarka",
    tagline: "Tandoor fired at 11, breads till midnight",
    cuisines: ["North Indian", "Punjabi", "Tandoor"],
    pureVeg: false,
    rating: 4.3,
    prepMinutes: 24,
    distanceKm: 0.8,
    priceTier: 0.95,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.01, zomato: 0 },
    memberPartner: ["swiggy", "zomato"],
    offers: [
      { channel: "swiggy", label: "50% off up to ₹100", percent: 50, cap: 100, minOrder: 249 },
      { channel: "zomato", label: "40% off up to ₹80", percent: 40, cap: 80, minOrder: 199 },
    ],
    menu: [
      ...NORTH_CORE,
      m("butter-chicken"),
      m("paneer-tikka"),
      m("laccha-paratha"),
      m("chicken-biryani"),
      m("veg-thali"),
    ],
  },
  {
    id: "sector-6-sweet-house",
    name: "Sector 6 Sweet House",
    localityId: "dwarka",
    tagline: "Mithai counter in front, thali kitchen behind",
    cuisines: ["North Indian", "Sweets", "Thali"],
    pureVeg: true,
    rating: 4.4,
    prepMinutes: 20,
    distanceKm: 1.4,
    priceTier: 1.05,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0, zomato: -0.01 },
    memberPartner: ["zomato"],
    offers: [{ channel: "zomato", label: "50% off up to ₹90", percent: 50, cap: 90, minOrder: 249 }],
    // Sweets are the house speciality and priced against the counter, not the
    // menu — the clearest case for an override rather than a tier.
    menu: [...NORTH_CORE, m("gulab-jamun", 55), m("veg-thali"), m("chole-bhature"), m("shahi-paneer")],
  },
  {
    id: "dhaba-est-1986",
    name: "Dhaba Est. 1986",
    localityId: "dwarka",
    tagline: "Highway portions at a city address",
    cuisines: ["North Indian", "Punjabi"],
    pureVeg: false,
    rating: 4.2,
    prepMinutes: 28,
    distanceKm: 2.6,
    priceTier: 1.15,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.01 },
    memberPartner: ["swiggy"],
    offers: [
      { channel: "swiggy", label: "60% off up to ₹120", percent: 60, cap: 120, minOrder: 349 },
      { channel: "ondc", label: "12% off up to ₹70", percent: 12, cap: 70, minOrder: 299 },
    ],
    menu: [
      ...NORTH_CORE,
      m("butter-chicken"),
      m("paneer-tikka"),
      m("laccha-paratha"),
      m("shahi-paneer"),
      m("veg-biryani"),
    ],
  },
  {
    id: "grand-imperial",
    name: "Grand Imperial",
    localityId: "dwarka",
    tagline: "Hotel restaurant — linen, live ghazals on Fridays",
    cuisines: ["North Indian", "Mughlai", "Fine dining"],
    pureVeg: false,
    rating: 4.6,
    prepMinutes: 35,
    distanceKm: 3.8,
    priceTier: 1.45,
    // Premium independents are the most common ONDC gap: the network's
    // catalogue skews to chains and value kitchens.
    listedOn: ["swiggy", "zomato", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.02 },
    memberPartner: ["zomato"],
    offers: [{ channel: "zomato", label: "20% off up to ₹150", percent: 20, cap: 150, minOrder: 599 }],
    menu: [
      ...NORTH_CORE,
      m("butter-chicken"),
      m("paneer-tikka"),
      m("chicken-biryani"),
      m("shahi-paneer"),
      m("laccha-paratha"),
    ],
  },

  // ----------------------------------------------------------- Indiranagar --
  {
    id: "corner-chai-and-chaat",
    name: "Corner Chai & Chaat",
    localityId: "indiranagar",
    tagline: "Two tables, one griddle, a queue at 6pm",
    cuisines: ["Street food", "North Indian", "Chaat"],
    pureVeg: true,
    rating: 4.1,
    prepMinutes: 12,
    distanceKm: 0.4,
    priceTier: 0.75,
    listedOn: ["swiggy", "ondc", "pickup"],
    markupAdjustment: {},
    memberPartner: [],
    offers: [{ channel: "ondc", label: "15% off up to ₹40", percent: 15, cap: 40, minOrder: 149 }],
    menu: [...NORTH_CORE, m("chole-bhature"), m("masala-chai"), m("masala-dosa"), m("veg-thali")],
  },
  {
    id: "namma-tiffin-room",
    name: "Namma Tiffin Room",
    localityId: "indiranagar",
    tagline: "Filter coffee and dosas from 6am",
    cuisines: ["South Indian", "Tiffin"],
    pureVeg: true,
    rating: 4.5,
    prepMinutes: 16,
    distanceKm: 0.6,
    priceTier: 0.85,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.02 },
    memberPartner: ["swiggy"],
    offers: [{ channel: "swiggy", label: "40% off up to ₹60", percent: 40, cap: 60, minOrder: 149 }],
    menu: [
      ...NORTH_CORE,
      m("masala-dosa", 95),
      m("veg-thali"),
      m("masala-chai"),
      m("chole-bhature"),
    ],
  },
  {
    id: "the-curry-company",
    name: "The Curry Company",
    localityId: "indiranagar",
    tagline: "North Indian gravies, ground fresh each morning",
    cuisines: ["North Indian", "Mughlai"],
    pureVeg: false,
    rating: 4.3,
    prepMinutes: 26,
    distanceKm: 2.4,
    priceTier: 1.1,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.01 },
    memberPartner: ["swiggy", "zomato"],
    offers: [
      { channel: "zomato", label: "50% off up to ₹100", percent: 50, cap: 100, minOrder: 299 },
      { channel: "swiggy", label: "40% off up to ₹90", percent: 40, cap: 90, minOrder: 299 },
    ],
    menu: [...NORTH_CORE, m("butter-chicken"), m("paneer-tikka"), m("shahi-paneer"), m("laccha-paratha")],
  },
  {
    id: "biryani-bhavan",
    name: "Biryani Bhavan",
    localityId: "indiranagar",
    tagline: "Sealed pots, opened at your table",
    cuisines: ["Biryani", "Hyderabadi"],
    pureVeg: false,
    rating: 4.2,
    prepMinutes: 30,
    distanceKm: 3.1,
    priceTier: 1.0,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.01, ondc: 0.005 },
    memberPartner: ["swiggy"],
    offers: [{ channel: "swiggy", label: "50% off up to ₹110", percent: 50, cap: 110, minOrder: 299 }],
    menu: [
      ...NORTH_CORE,
      m("chicken-biryani", 260),
      m("veg-biryani", 195),
      m("butter-chicken"),
      m("paneer-tikka"),
    ],
  },
  {
    id: "hundred-feet-kitchen",
    name: "100 Feet Kitchen",
    localityId: "indiranagar",
    tagline: "Small plates, natural wine, a very good naan",
    cuisines: ["Modern Indian", "Cafe"],
    pureVeg: false,
    rating: 4.6,
    prepMinutes: 32,
    distanceKm: 1.9,
    priceTier: 1.35,
    listedOn: ["swiggy", "zomato", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.02 },
    memberPartner: ["zomato"],
    offers: [{ channel: "zomato", label: "20% off up to ₹120", percent: 20, cap: 120, minOrder: 499 }],
    menu: [...NORTH_CORE, m("paneer-tikka"), m("butter-chicken"), m("laccha-paratha"), m("shahi-paneer")],
  },

  // ---------------------------------------------------------- Andheri West --
  {
    id: "shree-krishna-bhojanalay",
    name: "Shree Krishna Bhojanalay",
    localityId: "andheri-west",
    tagline: "Unlimited thali, no onion no garlic on request",
    cuisines: ["North Indian", "Gujarati", "Thali"],
    pureVeg: true,
    rating: 4.2,
    prepMinutes: 18,
    distanceKm: 0.7,
    priceTier: 0.85,
    listedOn: ["swiggy", "ondc", "pickup"],
    markupAdjustment: {},
    memberPartner: ["swiggy"],
    offers: [{ channel: "ondc", label: "12% off up to ₹60", percent: 12, cap: 60, minOrder: 199 }],
    menu: [...NORTH_CORE, m("veg-thali", 170), m("chole-bhature"), m("laccha-paratha"), m("masala-chai")],
  },
  {
    id: "versova-dhaba",
    name: "Versova Dhaba",
    localityId: "andheri-west",
    tagline: "Charpoy seating, tandoor going all evening",
    cuisines: ["North Indian", "Punjabi"],
    pureVeg: false,
    rating: 4.1,
    prepMinutes: 25,
    distanceKm: 1.2,
    priceTier: 1.0,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.01, zomato: 0.01 },
    memberPartner: ["swiggy", "zomato"],
    offers: [{ channel: "swiggy", label: "50% off up to ₹100", percent: 50, cap: 100, minOrder: 249 }],
    menu: [...NORTH_CORE, m("butter-chicken"), m("chicken-biryani"), m("paneer-tikka"), m("laccha-paratha")],
  },
  {
    id: "linking-road-thali",
    name: "Linking Road Thali Co.",
    localityId: "andheri-west",
    tagline: "One thali, seventeen bowls",
    cuisines: ["Thali", "North Indian", "Rajasthani"],
    pureVeg: true,
    rating: 4.4,
    prepMinutes: 22,
    distanceKm: 2.2,
    priceTier: 1.15,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { zomato: -0.01 },
    memberPartner: ["zomato"],
    offers: [{ channel: "zomato", label: "45% off up to ₹100", percent: 45, cap: 100, minOrder: 299 }],
    menu: [...NORTH_CORE, m("veg-thali"), m("shahi-paneer"), m("laccha-paratha"), m("veg-biryani")],
  },
  {
    id: "bombay-tandoor-house",
    name: "Bombay Tandoor House",
    localityId: "andheri-west",
    tagline: "Kebabs off the skewer, breads to order",
    cuisines: ["Mughlai", "Tandoor", "North Indian"],
    pureVeg: false,
    rating: 4.3,
    prepMinutes: 29,
    distanceKm: 3.4,
    priceTier: 1.25,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.02 },
    memberPartner: ["swiggy"],
    offers: [{ channel: "swiggy", label: "40% off up to ₹120", percent: 40, cap: 120, minOrder: 399 }],
    menu: [...NORTH_CORE, m("paneer-tikka", 290), m("butter-chicken"), m("chicken-biryani"), m("laccha-paratha")],
  },
  {
    id: "lokhandwala-grill-house",
    name: "Lokhandwala Grill House",
    localityId: "andheri-west",
    tagline: "Rooftop, imported grill, prices to match",
    cuisines: ["Modern Indian", "Grill", "Fine dining"],
    pureVeg: false,
    rating: 4.5,
    prepMinutes: 34,
    distanceKm: 4.2,
    priceTier: 1.4,
    listedOn: ["swiggy", "zomato", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.02 },
    memberPartner: ["zomato"],
    offers: [{ channel: "zomato", label: "25% off up to ₹200", percent: 25, cap: 200, minOrder: 699 }],
    menu: [...NORTH_CORE, m("paneer-tikka"), m("butter-chicken"), m("shahi-paneer"), m("laccha-paratha")],
  },

  // --------------------------------------------------------- Koregaon Park --
  {
    id: "swaad-veg-corner",
    name: "Swaad Veg Corner",
    localityId: "koregaon-park",
    tagline: "Home-style sabzi, refilled without asking",
    cuisines: ["North Indian", "Maharashtrian", "Thali"],
    pureVeg: true,
    rating: 4.1,
    prepMinutes: 17,
    distanceKm: 0.6,
    priceTier: 0.8,
    listedOn: ["swiggy", "ondc", "pickup"],
    markupAdjustment: {},
    memberPartner: [],
    offers: [{ channel: "ondc", label: "10% off up to ₹45", percent: 10, cap: 45, minOrder: 149 }],
    menu: [...NORTH_CORE, m("veg-thali", 155), m("chole-bhature"), m("masala-chai"), m("laccha-paratha")],
  },
  {
    id: "pune-punjabi-tadka",
    name: "Punjabi Tadka Pune",
    localityId: "koregaon-park",
    tagline: "Dal makhani on the stove since dawn",
    cuisines: ["North Indian", "Punjabi"],
    pureVeg: false,
    rating: 4.2,
    prepMinutes: 26,
    distanceKm: 0.9,
    priceTier: 0.95,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.01 },
    memberPartner: ["swiggy", "zomato"],
    offers: [
      { channel: "swiggy", label: "50% off up to ₹100", percent: 50, cap: 100, minOrder: 249 },
      { channel: "zomato", label: "40% off up to ₹90", percent: 40, cap: 90, minOrder: 249 },
    ],
    menu: [...NORTH_CORE, m("dal-makhani", 175), m("butter-chicken"), m("laccha-paratha"), m("paneer-tikka")],
  },
  {
    id: "north-star-dhaba",
    name: "North Star Dhaba",
    localityId: "koregaon-park",
    tagline: "Truckers' portions, students' prices",
    cuisines: ["North Indian", "Dhaba"],
    pureVeg: false,
    rating: 4.0,
    prepMinutes: 27,
    distanceKm: 1.6,
    priceTier: 1.05,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { zomato: 0.01 },
    memberPartner: ["swiggy"],
    offers: [{ channel: "ondc", label: "12% off up to ₹65", percent: 12, cap: 65, minOrder: 249 }],
    menu: [...NORTH_CORE, m("butter-chicken"), m("veg-biryani"), m("laccha-paratha"), m("chole-bhature")],
  },
  {
    id: "deccan-biryani-co",
    name: "Deccan Biryani Co.",
    localityId: "koregaon-park",
    tagline: "Dum-cooked, never stirred",
    cuisines: ["Biryani", "Hyderabadi"],
    pureVeg: false,
    rating: 4.3,
    prepMinutes: 31,
    distanceKm: 3.9,
    priceTier: 1.1,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.02, ondc: 0.005 },
    memberPartner: ["swiggy"],
    offers: [{ channel: "swiggy", label: "50% off up to ₹110", percent: 50, cap: 110, minOrder: 349 }],
    menu: [...NORTH_CORE, m("chicken-biryani"), m("veg-biryani"), m("paneer-tikka"), m("butter-chicken")],
  },
  {
    id: "lane-5-cafe",
    name: "Lane 5 Cafe",
    localityId: "koregaon-park",
    tagline: "Espresso, sourdough, and a surprisingly good paneer",
    cuisines: ["Cafe", "Modern Indian"],
    pureVeg: false,
    rating: 4.5,
    prepMinutes: 30,
    distanceKm: 2.8,
    priceTier: 1.35,
    listedOn: ["swiggy", "zomato", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.02 },
    memberPartner: ["zomato"],
    offers: [{ channel: "zomato", label: "20% off up to ₹110", percent: 20, cap: 110, minOrder: 499 }],
    menu: [...NORTH_CORE, m("paneer-tikka"), m("shahi-paneer"), m("laccha-paratha"), m("masala-chai")],
  },

  // --------------------------------------------------------- Banjara Hills --
  {
    id: "sri-krishna-tiffins",
    name: "Sri Krishna Tiffins",
    localityId: "banjara-hills",
    tagline: "Idli by 7, dosa till 11",
    cuisines: ["South Indian", "Tiffin"],
    pureVeg: true,
    rating: 4.3,
    prepMinutes: 15,
    distanceKm: 0.5,
    priceTier: 0.8,
    listedOn: ["swiggy", "ondc", "pickup"],
    markupAdjustment: {},
    memberPartner: [],
    offers: [{ channel: "ondc", label: "10% off up to ₹40", percent: 10, cap: 40, minOrder: 149 }],
    menu: [...NORTH_CORE, m("masala-dosa", 85), m("veg-thali"), m("masala-chai"), m("chole-bhature")],
  },
  {
    id: "road-no-12-biryani",
    name: "Road No. 12 Biryani",
    localityId: "banjara-hills",
    tagline: "Kacchi dum, mirchi ka salan on the side",
    cuisines: ["Biryani", "Hyderabadi"],
    pureVeg: false,
    rating: 4.4,
    prepMinutes: 30,
    distanceKm: 1.3,
    priceTier: 1.1,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.01 },
    memberPartner: ["swiggy", "zomato"],
    offers: [
      { channel: "swiggy", label: "50% off up to ₹120", percent: 50, cap: 120, minOrder: 349 },
      { channel: "zomato", label: "50% off up to ₹100", percent: 50, cap: 100, minOrder: 299 },
    ],
    menu: [...NORTH_CORE, m("chicken-biryani", 265), m("veg-biryani"), m("butter-chicken"), m("paneer-tikka")],
  },
  {
    id: "banjara-dhaba",
    name: "Banjara Dhaba",
    localityId: "banjara-hills",
    tagline: "Open till 2am, which is the point",
    cuisines: ["North Indian", "Dhaba"],
    pureVeg: false,
    rating: 4.0,
    prepMinutes: 24,
    distanceKm: 2.7,
    priceTier: 0.95,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.01 },
    memberPartner: ["swiggy"],
    offers: [{ channel: "swiggy", label: "40% off up to ₹80", percent: 40, cap: 80, minOrder: 249 }],
    menu: [...NORTH_CORE, m("butter-chicken"), m("laccha-paratha"), m("chole-bhature"), m("veg-biryani")],
  },
  {
    id: "hyderabad-house-kitchen",
    name: "Hyderabad House Kitchen",
    localityId: "banjara-hills",
    tagline: "Mughlai gravies, slow and heavy",
    cuisines: ["Mughlai", "North Indian"],
    pureVeg: false,
    rating: 4.2,
    prepMinutes: 28,
    distanceKm: 2.1,
    priceTier: 1.2,
    listedOn: ["swiggy", "zomato", "ondc", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.01 },
    memberPartner: ["zomato"],
    offers: [{ channel: "zomato", label: "40% off up to ₹110", percent: 40, cap: 110, minOrder: 399 }],
    menu: [...NORTH_CORE, m("shahi-paneer"), m("butter-chicken"), m("paneer-tikka"), m("chicken-biryani")],
  },
  {
    id: "nawabi-dastarkhwan",
    name: "Nawabi Dastarkhwan",
    localityId: "banjara-hills",
    tagline: "Silver thalis, forty-year-old recipes",
    cuisines: ["Mughlai", "Fine dining", "Awadhi"],
    pureVeg: false,
    rating: 4.6,
    prepMinutes: 36,
    distanceKm: 3.2,
    priceTier: 1.35,
    listedOn: ["swiggy", "zomato", "pickup"],
    markupAdjustment: { swiggy: 0.02, zomato: 0.02 },
    memberPartner: ["zomato"],
    offers: [{ channel: "zomato", label: "25% off up to ₹180", percent: 25, cap: 180, minOrder: 649 }],
    menu: [...NORTH_CORE, m("butter-chicken"), m("chicken-biryani"), m("paneer-tikka"), m("shahi-paneer")],
  },
];

export const RESTAURANT_BY_ID = new Map(RESTAURANTS.map((r) => [r.id, r]));

export function restaurantsIn(localityId: string): Restaurant[] {
  return RESTAURANTS.filter((restaurant) => restaurant.localityId === localityId);
}
